<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/activity.proto

namespace GPBMetadata\Protos;

class Activity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a1570726f746f732f61637469766974792e70726f746f228b010a" .
            "0c41637469766974794974656d120a0a024964180120012803120d0a0554" .
            "69746c6518022001280912100a08496d61676555726c1803200128091213" .
            "0a0b4465736372697074696f6e180420012809121b0a0454797065180520" .
            "01280e320d2e416374697669747954797065120e0a064c6162656c731806" .
            "20032809120c0a044c696e6b1807200128092a320a0c4163746976697479" .
            "54797065120b0a0741525449434c451000120b0a07504f44434153541001" .
            "12080a04464143541002422c5a12696e7465726e616c2f67656e65726174" .
            "6564c2020950726f746f74797065ca020947656e65726174656462067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

