<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTf2prgF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTf2prgF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTf2prgF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTf2prgF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTf2prgF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tf2prgF',
    'container.build_id' => '6611f19e',
    'container.build_time' => 1631888381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTf2prgF');
